version: '3.8'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Pass123
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - backend_net

  app:
    build: .
    container_name: backend_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=sqlserver://sa:YourStrong@Pass123@db:1433;database=mi_db;encrypt=true;trustServerCertificate=true
    networks:
      - backend_net

volumes:
  sqlserver_data:

networks:
  backend_net: