services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Pass123
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - backend_net

  app:
    build: .
    container_name: backend_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PORT=${PORT}
    networks:
      - backend_net
    command: sh -c "npx prisma generate && node src/server.js"

volumes:
  sqlserver_data:

networks:
  backend_net: